# ビルド環境
FROM node:14.16.0-buster-slim

ENV NODE_ENV=production

RUN apt-get update && apt-get install -y \
    curl

# アプリケーションソースをバンドル
COPY /frontend /usr/src/frontend

WORKDIR /usr/src/frontend
RUN npm cache verify --force && npm install && npm rebuild node-sass --force && npm run build

CMD [ "npm", "start" ]