version: "3"

services:
  web:
    env_file: ./next-app/.env
    build:
      context: .
      dockerfile: ./next-app/Dockerfile
    image: dobon_web
    container_name: dobon_web
    command: npm run dev
    environment:
      NODE_ENV: development
    volumes:
      - ./next-app:/usr/src/next-app
      - /usr/src/next-app/node_modules
    ports:
      - "3000:3000"
    tty: true