version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: dobon_api
    container_name: dobon_api
    command: npm run install && npm run tsc && npm run prisma:generate && npm run start
    volumes:
      - ./api:/usr/src/api
      - ./api/node_modules:/usr/src/api/node_modules
    ports:
      - "8080:8080"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=production
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.web
    image: dobon_web
    container_name: dobon_web
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend:/usr/src/frontend
      - ./frontend/node_modules:/usr/src/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true
