version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: dobon_api
    container_name: dobon_api
    volumes:
      - ./api:/usr/src/api
      - ./api/node_modules:/usr/src/api/node_modules
    ports:
      - "8080:8080"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: dobon_web
    container_name: dobon_web
    volumes:
      - ./frontend:/frontend
      - ./frontend/node_modules:/usr/src/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mongo
  mongo:
    image: mongo
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
