# ビルド環境
FROM node:14.16.0-buster-slim

# アプリケーションソースをバンドル
COPY /frontend /usr/src/frontend

WORKDIR /usr/src/frontend
RUN npm cache verify --force && npm install && npm rebuild node-sass --force

# アプリケーションを実行するコマンド定義
EXPOSE 3000

CMD npm run dev
