version: "3"

services:
  api:
    env_file: .env
    build:
      context: ./api
      dockerfile: Dockerfile
    image: dobon_api
    container_name: dobon_api
    command: npm run dev-api
    volumes:
      - ./api:/usr/src/api
      - ./api/node_modules:/usr/src/api/node_modules
    ports:
      - "8080:8080"
    tty: true
    depends_on:
      - db
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
  web:
    env_file: .env
    build:
      context: .
      dockerfile: ./next-app/Dockerfile
    image: dobon_web
    container_name: dobon_web
    command: npm run dev
    environment:
      NODE_ENV: development
    volumes:
      - ./next-app:/usr/src/next-app
      - ./next-app/node_modules:/usr/src/next-app/node_modules
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: dobon_db
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    tty: true
volumes:
  db: