FROM node:14.16.0-buster-slim
ENV HOST 0.0.0.0

RUN apt-get update && apt-get install -y \
    curl

WORKDIR /usr/src/frontend
COPY /front/package*.json /usr/src/frontend
RUN npm install

COPY /front /usr/src/frontend

EXPOSE 3000