#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# commitファイルが存在するディレクトリでtest/lintを実行する
files=($(git diff --cached --name-only)) # commit対象ファイルパスを配列に格納

if printf '%s\n' ${files[@]} | egrep "^next-app/**/*" | egrep "\.(js$|ts$|jsx$|tsx$)" > /dev/null >&2; then
  echo "/next-app directory test & lint starting"
  cd next-app
  npx lint-staged
  npm run test
fi

if printf '%s\n' ${files[@]} | egrep "^api/**/*" | egrep "\.(js$|ts$|jsx$|tsx$|vue$)" > /dev/null >&2; then
  echo "/api directory test starting"
  #cd api
  #npm run test 
fi

exit 0